spring.application.name=ConnectHub

# Prod Database Settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# In production, use validate or update depending on DB migration strategy
spring.jpa.hibernate.ddl-auto=update
# Turn off show-sql in production for performance and security
spring.jpa.show-sql=false

# Prod JWT Settings
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Prod CORS
cors.allowed-origins=${FRONTEND_URL:*}
